'use strict';

// Bundles the web client into ./web (Capacitor's webDir) and writes config.js
// pointing the app at the public game server.
//
// Usage:
//   SF_SERVER_URL=https://strategic-football.onrender.com npm run web:build

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const PUBLIC = path.join(ROOT, 'public');
const LIB = path.join(ROOT, 'lib');
const WEB = path.join(ROOT, 'web');

function copyDir(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDir(from, to);
    else fs.copyFileSync(from, to);
  }
}

const serverUrl = process.env.SF_SERVER_URL || '';
if (!serverUrl) {
  console.warn('[web:build] WARNING: SF_SERVER_URL not set. config.js will keep the default (page origin).');
  console.warn('[web:build] For the packaged Android app set it, e.g. SF_SERVER_URL=https://your-app.onrender.com');
}

fs.rmSync(WEB, { recursive: true, force: true });
fs.mkdirSync(WEB, { recursive: true });
copyDir(PUBLIC, WEB);
copyDir(LIB, path.join(WEB, 'lib'));

const configJs =
  '// Generated by scripts/build-web.js - do not edit.\n' +
  'window.SF_SERVER_URL = ' + JSON.stringify(serverUrl) + ';\n';
fs.writeFileSync(path.join(WEB, 'config.js'), configJs);

console.log('[web:build] Bundled web assets -> web/ (server: ' + (serverUrl || 'page origin') + ')');